baseURL = "https://sendipad.github.io/uph/"
title = "Unified Party Hub"
theme = "book"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
languageCode = "en-us"

[params]
  BookLogo = "uph-logo.png"
  BookSearch = true
  BookSearchIndex = true
  BookRepo = "https://github.com/sendipad/uph"
  BookEditPath = "edit/docs/content"
  BookEdit = true

  BookTheme = "auto"
  customCSS = ["custom.css"]
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"
  [languages.ar]
    languageName = "العربية"
    weight = 2
    contentDir = "content/ar"
    languageDirection = "rtl"

[menu]

  [[menu.main]]
    identifier = "documentation"
    name = "Documentation"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "quickstart"
    name = "Quick Start"
    url = "/quick-start/"
    weight = 2

  [[menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/sendipad/uph"
    weight = 3
    pre = "<i class='fab fa-github'></i> "  # optional, adds GitHub icon

[taxonomies]
  tag = "tags"
  category = "categories"
