name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          db-root-password: ${{ secrets.DB_ROOT_PASSWORD }}
          disable-socketio: true
          build-assets: true

      - name: Run tests
        shell: bash
        run: |
          source env/bin/activate
          bench --site test_site run-tests --app uph --doctype "Party Master"

      - name: Print bench log (on failure)
        if: failure()
        run: |
          cat bench_start.log || echo "No bench_start.log found"
          ls -l logs || echo "No logs directory found"
